spring:
  application:
    name: CART-SERVICE
  data:
    mongodb:
        uri: mongodb://localhost:27017/cart_service_db
        auto-index-creation: true
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    com.prem.ecommerce.product: DEBUG
