server:
  port: 8084

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:mysql:///order_service_db
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework: INFO
