spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    com.prem.ecommerce.product: DEBUG
