spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/prem123
    username: root
    password: admin
    # url: jdbc:postgresql://localhost:5432/productdb
    # username: postgres
    # password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    com.prem.ecommerce.product: DEBUG
